### ISSUE TITLE
MapsIndoors SDK Crashes

### ISSUE THREAD

**Issue by dhananjaykumardubey** [MapsIndoors/MapsIndoorsIOS#1]
Hi ,

I added mapsIndoors SDK through pod in project. But at compile time, it crashes with an error fatal error :"image is missing" in mapsindoors.

Its very appreciable if, I can know if I am missing something.

**Comment by Daniel-Nielsen** [comment]
Thanks for your issue. Please, if this issue is still persistent at current version, submit a request at https://www.mapspeople.com/developers/support
