### ISSUE TITLE
MapsIndoors causes Firebase to crash

### ISSUE THREAD

**Issue by MaartenZonneveld** [MapsIndoors/MapsIndoorsIOS#2]
I'm experiencing an issue when using both Firebase and MapsIndoors in the same project using cocoapods.

More specifically, Firebase crashes while executing it's `configure` method. The crash implies a `exc_bad_access` on `+[NSString(UrlRequest) stringWithContentsOfURL:encoding:error:]_block_invoke:`.

After digging a little deeper I found that MapsIndoors provides a category for `NSString` in `NSString+UrlRequest.h` which provides the following method:
```
+ (nullable NSString*)stringWithContentsOfURL:(nonnull NSURL *)url
                            encoding:(NSStringEncoding)enc
                               error:(NSError * _Nullable * _Nullable)error;
```

When I remove the MapsIndoors pod from my project, the crash no longer occurs. I believe Firebase accidentally uses this method from the MapsIndoors framework. Frameworks should not expose extensions/categories on Foundation components like this, as it will cause trouble when an other component uses it's own (same method).

Some configuration info:
```
Xcode 8.3.2
Cocoapods 1.2.1
MapsIndoors 1.6.35
Firebase 4.0.2
```

Let me know if you need more information to resolve this issue!

**Comment by Daniel-Nielsen** [comment]
Thanks for your request. This should be fixed by version 1.8.96-beta. Can you test this out?
