### ISSUE TITLE
Error in running MapsIndoor

### ISSUE THREAD

**Issue by marwarammal91** [MapsIndoors/MapsIndoorsIOS#23]
I am getting this error when running the code:

`dyld: Library not loaded: @rpath/MQTTClient.framework/MQTTClient

  Referenced from: /Users/Library/Developer/Xcode/DerivedData/VisitSaudi-efmepccwgbiwnbbwomdwlqvnlfad/Build/Products/Dev-iphonesimulator/MapsIndoors.framework/MapsIndoors

  Reason: image not found`

**Comment by ChristianWolf-mapspeople** [comment]
If you still experience this issue please contact [MapsPeople support](https://mapspeople.atlassian.net/servicedesk/customer/portals)
