### ISSUE TITLE
User's Location is not visible using v3.39.0

### ISSUE THREAD

**Issue by juancarlosdmz** [MapsIndoors/MapsIndoorsIOS#25]
I ran the Demo target in the Example folder, and for the latest version (3.39.0) my user location is not visible in the **Show My Location** section.
Then I downloaded the previous version (3.38.0) and I notice it was working with the same environment.

**Comment by lvdwiele** [comment]
I have the same issue on 3.39.0. 
Worked fine with version 3.34.0.

**Comment by juancarlosdmz** [comment]
> I have the same issue on 3.39.0.
> Worked fine with version 3.34.0.

I received a response and there is a workaround that it works:

> Please try the following as a workaround: Try to make a copy of the asset MyLocationDirection and name the copy Mylocation (note the lower casing) that should make the user position show while we work on fixing the bug in the SDK. Please let us know if you need additional information.

you can get that asset from the example.

cheers!

**Comment by lvdwiele** [comment]
That works great, thanks!

> > I have the same issue on 3.39.0.
> > Worked fine with version 3.34.0.
> 
> I received a response and there is a workaround that it works:
> 
> > Please try the following as a workaround: Try to make a copy of the asset MyLocationDirection and name the copy Mylocation (note the lower casing) that should make the user position show while we work on fixing the bug in the SDK. Please let us know if you need additional information.
> 
> you can get that asset from the example.
> 
> cheers!
