### ISSUE TITLE
ARC errors

### ISSUE THREAD

**Issue by gulzatique** [MapsIndoors/MapsIndoorsIOS#3]
Hi I am having these issues with the project
havent added any new lines of code yet http://joxi.ru/D2PGGnWud1da7m

**Comment by Daniel-Nielsen** [comment]
Hi @gulzatique, the example you are referring to does not seem to be the Example code in this project, where did you retrieve the sample code?

**Comment by gulzatique** [comment]
oh sorry that was my terrible mistake )
