### ISSUE TITLE
No such module 'MapsIndoors'

### ISSUE THREAD

**Issue by karan7698007** [MapsIndoors/MapsIndoorsIOS#38]
Can anybody guide on this issue?
<img width="902" alt="Screenshot 2022-11-20 at 5 06 21 PM" src="https://user-images.githubusercontent.com/15748915/202899832-225ca93e-f9eb-4d9a-bd3a-4821c32031cf.png">

**Comment by ChristianWolf-mapspeople** [comment]
If you still experience this issue please contact [MapsPeople support](https://mapspeople.atlassian.net/servicedesk/customer/portals)
