### ISSUE TITLE
"Show Location Demo" crashes

### ISSUE THREAD

**Issue by TomTasche** [MapsIndoors/MapsIndoorsIOS#5]
Cloning the latest version of master, running pod install, executing the app on a simulator and clicking "Show Location Demo" crashes as follows:
<img width="1680" alt="screenshot 2019-01-16 at 15 51 29" src="https://user-images.githubusercontent.com/128734/51256961-e6441d80-19a6-11e9-9292-3eeababf6f24.png">

Other samples like "Location Details Demo" work fine.

Same crash occurs on a real device (iPhone 8).

Any idea what could be wrong?

**Comment by Daniel-Nielsen** [comment]
I can't reproduce this issue in master, but it might be an issue with our 3.0.0-alpha SDK which is not stable. Can you supply the version of the SDK either by looking at `podfile.lock` or check the log on runtime?

**Comment by TomTasche** [comment]
Thanks, I think this was caused by me accidentally testing the project created after running "pod try MapsIndoors". I made sure to use the cloned version of your repository now, updated CocoaPods binaries (used an old version before) and now it works fine.
