### ISSUE TITLE
Info window closes when moving map view, using search results

### ISSUE THREAD

**Issue by ntorring** [MapsIndoors/MapsIndoorsIOS#6]
This occurs in the demo application for "Show Multiple Locations Demo".
Selection an annotation, opens the info window, moves the map, and then closes the window again.

**Comment by Daniel-Nielsen** [comment]
Thank you @ntorring, I am able to reproduce. Will let you know when it's fixed...

**Comment by Daniel-Nielsen** [comment]
This issue is fixed in 3.5.0
