### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by alice05** [MapsIndoors/MapsIndoorsIOS#7]
We have tested the app  in device and simulator. It was working fine in development environment. Then we pushed the build in testflight. After downloading and launching the app from test flight it crashes. Here I found the following logs in crashlythics. I believe it crashes in mapsindoors sdk. 

MapsIndoor SDK version: 3.5.0

**Crashlytics log:**

Crashed: com.twitter.crashlytics.ios.exception
0  MyApp                      0x10117c120 CLSProcessRecordAllThreads + 376 (CLSProcess.c:376)
1  MyApp                      0x10117c508 CLSProcessRecordAllThreads + 407 (CLSProcess.c:407)
2  MyApp                      0x10116c21c CLSHandler + 26 (CLSHandler.m:26)
3  MyApp                      0x10117a734 __CLSExceptionRecord_block_invoke + 199 (CLSException.mm:199)
4  libdispatch.dylib              0x212a057d4 _dispatch_client_callout + 16
5  libdispatch.dylib              0x2129b3c1c _dispatch_lane_barrier_sync_invoke_and_complete + 56
6  MyApp                      0x10117a1dc CLSExceptionRecord + 206 (CLSException.mm:206)
7  MyApp                      0x101179cf8 CLSTerminateHandler() + 265 (CLSException.mm:265)
8  libc++abi.dylib                0x212194838 std::__terminate(void (*)()) + 16
9  libc++abi.dylib                0x2121948c4 std::terminate() + 84
10 MyApp                      0x1016eca3c void boost::geometry::index::detail::rtree::visitors::detail::insert<std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int>, std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int>, boost::geometry::index::detail::rtree::options<boost::geometry::index::quadratic<16ul, 4ul>, boost::geometry::index::detail::rtree::insert_default_tag, boost::geometry::index::detail::rtree::choose_by_content_diff_tag, boost::geometry::index::detail::rtree::split_default_tag, boost::geometry::index::detail::rtree::quadratic_tag, boost::geometry::index::detail::rtree::node_variant_static_tag>, boost::geometry::index::detail::translator<boost::geometry::index::indexable<std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int> >, boost::geometry::index::equal_to<std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int> > >, boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, boost::geometry::index::detail::rtree::allocators<boost::container::new_allocator<std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int> >, std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int>, boost::geometry::index::quadratic<16ul, 4ul>, boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, boost::geometry::index::detail::rtree::node_variant_static_tag> >::split<boost::geometry::index::detail::rtree::variant_leaf<std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int>, boost::geometry::index::quadratic<16ul, 4ul>, boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, boost::geometry::index::detail::rtree::allocators<boost::container::new_allocator<std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int> >, std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int>, boost::geometry::index::quadratic<16ul, 4ul>, boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, boost::geometry::index::detail::rtree::node_variant_static_tag>, boost::geometry::index::detail::rtree::node_variant_static_tag> >(boost::geometry::index::detail::rtree::variant_leaf<std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int>, boost::geometry::index::quadratic<16ul, 4ul>, boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, boost::geometry::index::detail::rtree::allocators<boost::container::new_allocator<std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int> >, std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int>, boost::geometry::index::quadratic<16ul, 4ul>, boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, boost::geometry::index::detail::rtree::node_variant_static_tag>, boost::geometry::index::detail::rtree::node_variant_static_tag>&) const + 21744
11 MyApp                      0x1016ec5e4 void boost::geometry::index::detail::rtree::visitors::detail::insert<std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int>, std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int>, boost::geometry::index::detail::rtree::options<boost::geometry::index::quadratic<16ul, 4ul>, boost::geometry::index::detail::rtree::insert_default_tag, boost::geometry::index::detail::rtree::choose_by_content_diff_tag, boost::geometry::index::detail::rtree::split_default_tag, boost::geometry::index::detail::rtree::quadratic_tag, boost::geometry::index::detail::rtree::node_variant_static_tag>, boost::geometry::index::detail::translator<boost::geometry::index::indexable<std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int> >, boost::geometry::index::equal_to<std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int> > >, boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, boost::geometry::index::detail::rtree::allocators<boost::container::new_allocator<std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int> >, std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int>, boost::geometry::index::quadratic<16ul, 4ul>, boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, boost::geometry::index::detail::rtree::node_variant_static_tag> >::post_traverse<boost::geometry::index::detail::rtree::variant_leaf<std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int>, boost::geometry::index::quadratic<16ul, 4ul>, boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, boost::geometry::index::detail::rtree::allocators<boost::container::new_allocator<std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int> >, std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int>, boost::geometry::index::quadratic<16ul, 4ul>, boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, boost::geometry::index::detail::rtree::node_variant_static_tag>, boost::geometry::index::detail::rtree::node_variant_static_tag> >(boost::geometry::index::detail::rtree::variant_leaf<std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int>, boost::geometry::index::quadratic<16ul, 4ul>, boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, boost::geometry::index::detail::rtree::allocators<boost::container::new_allocator<std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int> >, std::__1::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, int>, boost::geometry::index::quadratic<16ul, 4ul>, boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, boost::geometry::index::detail::rtree::node_variant_static_tag>, boost::geometry::index::detail::rtree::node_variant_static_tag>&) + 20632
12 MyApp                      0x1016e451c MICommon::LocationServiceImpl::evaluateLocationForDataStore(MICommon::Location const&) + 43156
13 MyApp                      0x1016e5554 MICommon::LocationServiceImpl::onLocationsUpdated(std::__1::vector<MICommon::Location, std::__1::allocator<MICommon::Location> > const&, std::__1::shared_ptr<MICommon::LocationSource> const&) + 47308
14 MyApp                      0x1016f8280 -[MILocationsObserverCppProxy onLocationsUpdated:source:] + 1856
15 MyApp                      0x101742e68 __46-[MPLocationService onLocationsUpdate:source:]_block_invoke_2 + 295600
16 libdispatch.dylib              0x212a04a38 _dispatch_call_block_and_release + 24
17 libdispatch.dylib              0x212a057d4 _dispatch_client_callout + 16
18 libdispatch.dylib              0x2129ae324 _dispatch_lane_serial_drain$VARIANT$mp + 592
19 libdispatch.dylib              0x2129aee40 _dispatch_lane_invoke$VARIANT$mp + 428
20 libdispatch.dylib              0x2129b74ac _dispatch_workloop_worker_thread + 596
21 libsystem_pthread.dylib        0x212be6114 _pthread_wqthread + 304
22 libsystem_pthread.dylib        0x212be8cd4 start_wqthread + 4

**Here is the device log**

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  15

Application Specific Information:
abort() called

Thread 15 name:  Dispatch queue: com.mapsindoors.MPLocationService
Thread 15 Crashed:
0   libsystem_kernel.dylib        	0x0000000212b630dc __pthread_kill + 8
1   libsystem_pthread.dylib       	0x0000000212bdc094 pthread_kill$VARIANT$mp + 380
2   libsystem_c.dylib             	0x0000000212abbf4c __abort + 152
3   libsystem_c.dylib             	0x0000000212abbeb4 __abort + 0
4   libc++abi.dylib               	0x0000000212188788 __cxa_bad_cast + 0
5   libc++abi.dylib               	0x000000021218891c default_terminate_handler+ 6428 () + 284
6   libobjc.A.dylib               	0x000000021219fe10 _objc_terminate+ 24080 () + 140
7   MyApp                     	0x0000000100fb5fdc _hidden#69896_ + 3645404 (__hidden#69918_:0)
8   libc++abi.dylib               	0x0000000212194838 std::__terminate(void (*)+ 55352 ()) + 16
9   libc++abi.dylib               	0x00000002121948c4 std::terminate+ 55492 () + 84
10  MyApp                     	0x000000010152395c _hidden#119370_ + 892
11  MyApp                     	0x0000000101523504 _hidden#119368_ + 108
12  MyApp                     	0x000000010151b43c _hidden#119210_ + 284
13  MyApp                     	0x000000010151c474 _hidden#119215_ + 176
14  MyApp                     	0x000000010152f1a0 _hidden#119754_ + 120
15  MyApp                     	0x0000000101579d88 _hidden#121999_ + 252
16  libdispatch.dylib             	0x0000000212a04a38 _dispatch_call_block_and_release + 24
17  libdispatch.dylib             	0x0000000212a057d4 _dispatch_client_callout + 16
18  libdispatch.dylib             	0x00000002129ae324 _dispatch_lane_serial_drain$VARIANT$mp + 592
19  libdispatch.dylib             	0x00000002129aee40 _dispatch_lane_invoke$VARIANT$mp + 428
20  libdispatch.dylib             	0x00000002129b74ac _dispatch_workloop_worker_thread + 596
21  libsystem_pthread.dylib       	0x0000000212be6114 _pthread_wqthread + 304
22  libsystem_pthread.dylib       	0x0000000212be8cd4 start_wqthread + 4

**Comment by Daniel-Nielsen** [comment]
@alice05 Thanks for letting us know and sorry for letting you wait. I received and answered your support request though mapsindoors.com/support, so I don't expect responses here. 

This looks a lot like a known issue that happens when you have bitcode enabled. If this is a bitcode issue, an immediate workaround is to disable bitcode. We are in dialog with Apple regarding the bitcode issue, and I will let you know when we have a resolution.
